function out1 = Calibration_OMC_IMU_p(in1)
%CALIBRATION_OMC_IMU_P
%    OUT1 = CALIBRATION_OMC_IMU_P(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-May-2021 17:03:08

quat1 = in1(:,1);
quat2 = in1(:,2);
quat3 = in1(:,3);
quat4 = in1(:,4);
t2 = quat4.^2;
t3 = t2.*2.0;
t4 = -t3;
out1 = [atan2(quat1.*quat2.*2.0-quat3.*quat4.*2.0,t4-quat2.^2.*2.0+1.0),atan2(quat1.*quat3.*2.0-quat2.*quat4.*2.0,t4-quat3.^2.*2.0+1.0),asin(quat1.*quat4.*2.0+quat2.*quat3.*2.0)];
