function [wbiasd,abiasd,wbiasd_jac,abiasd_jac] = Calibration_OMC_IMU_cost_imubias(in1,t_bias,dt_bias)
%CALIBRATION_OMC_IMU_COST_IMUBIAS
%    [WBIASD,ABIASD,WBIASD_JAC,ABIASD_JAC] = CALIBRATION_OMC_IMU_COST_IMUBIAS(IN1,T_BIAS,DT_BIAS)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Jun-2021 13:02:16

cabias1_1 = in1(:,10);
cabias1_2 = in1(:,13);
cabias1_3 = in1(:,16);
cabias2_1 = in1(:,11);
cabias2_2 = in1(:,14);
cabias2_3 = in1(:,17);
cabias3_1 = in1(:,12);
cabias3_2 = in1(:,15);
cabias3_3 = in1(:,18);
cwbias1_1 = in1(:,1);
cwbias1_2 = in1(:,4);
cwbias1_3 = in1(:,7);
cwbias2_1 = in1(:,2);
cwbias2_2 = in1(:,5);
cwbias2_3 = in1(:,8);
cwbias3_1 = in1(:,3);
cwbias3_2 = in1(:,6);
cwbias3_3 = in1(:,9);
t2 = t_bias.*2.0;
t3 = 1.0./dt_bias;
t4 = t_bias-1.0;
t5 = t2-1.0;
wbiasd = [t3.*(cwbias1_1.*t4-cwbias2_1.*t5+cwbias3_1.*t_bias);t3.*(cwbias1_2.*t4-cwbias2_2.*t5+cwbias3_2.*t_bias);t3.*(cwbias1_3.*t4-cwbias2_3.*t5+cwbias3_3.*t_bias)];
if nargout > 1
    abiasd = [t3.*(cabias1_1.*t4-cabias2_1.*t5+cabias3_1.*t_bias);t3.*(cabias1_2.*t4-cabias2_2.*t5+cabias3_2.*t_bias);t3.*(cabias1_3.*t4-cabias2_3.*t5+cabias3_3.*t_bias)];
end
if nargout > 2
    t6 = t3.*t_bias;
    t7 = t3.*t4;
    t8 = t3.*t5;
    t9 = -t8;
    wbiasd_jac = reshape([t7,0.0,0.0,t9,0.0,0.0,t6,0.0,0.0,0.0,t7,0.0,0.0,t9,0.0,0.0,t6,0.0,0.0,0.0,t7,0.0,0.0,t9,0.0,0.0,t6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,18]);
end
if nargout > 3
    abiasd_jac = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7,0.0,0.0,t9,0.0,0.0,t6,0.0,0.0,0.0,t7,0.0,0.0,t9,0.0,0.0,t6,0.0,0.0,0.0,t7,0.0,0.0,t9,0.0,0.0,t6],[3,18]);
end
