function out1 = Calibration_OMC_IMU_pd(in1,in2)
%CALIBRATION_OMC_IMU_PD
%    OUT1 = CALIBRATION_OMC_IMU_PD(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Jun-2021 12:05:17

quat1 = in1(:,1);
quat2 = in1(:,2);
quat3 = in1(:,3);
quat4 = in1(:,4);
w1 = in2(:,1);
w2 = in2(:,2);
w3 = in2(:,3);
t2 = quat2.^2;
t3 = quat3.^2;
t4 = quat4.^2;
t5 = quat1.*quat2.*2.0;
t6 = quat1.*quat3.*2.0;
t7 = quat2.*quat4.*2.0;
t8 = quat3.*quat4.*2.0;
t14 = (quat1.*w1)./2.0;
t15 = (quat1.*w2)./2.0;
t16 = (quat2.*w1)./2.0;
t17 = (quat1.*w3)./2.0;
t18 = (quat2.*w2)./2.0;
t19 = (quat3.*w1)./2.0;
t20 = (quat2.*w3)./2.0;
t21 = (quat3.*w2)./2.0;
t22 = (quat4.*w1)./2.0;
t23 = (quat3.*w3)./2.0;
t24 = (quat4.*w2)./2.0;
t25 = (quat4.*w3)./2.0;
t9 = t2.*2.0;
t10 = t3.*2.0;
t11 = t4.*2.0;
t12 = -t7;
t13 = -t8;
t26 = -t19;
t27 = -t20;
t28 = -t24;
t35 = t16+t21+t25;
t29 = t5+t13;
t30 = t6+t12;
t31 = t9+t11-1.0;
t32 = t10+t11-1.0;
t36 = t17+t18+t26;
t37 = t15+t22+t27;
t38 = t14+t23+t28;
t33 = t31.^2;
t34 = t32.^2;
t39 = quat4.*t36.*4.0;
out1 = [(t33.*((quat2.*t35.*2.0-quat1.*t38.*2.0+quat3.*t36.*2.0+quat4.*t37.*2.0)./t31+(t29.*(t39+quat2.*t38.*4.0))./t33))./(t33+t29.^2),(t34.*((quat1.*t37.*-2.0+quat2.*t36.*2.0+quat3.*t35.*2.0+quat4.*t38.*2.0)./t32+(t30.*(t39+quat3.*t37.*4.0))./t34))./(t34+t30.^2),1.0./sqrt(-(quat1.*quat4.*2.0+quat2.*quat3.*2.0).^2+1.0).*(quat1.*t36.*2.0+quat2.*t37.*2.0-quat4.*t35.*2.0+quat3.*t38.*2.0)];
